[build.environment]
  NODE_VERSION = "22"
  RUBY_VERSION = "3.3.4"

[build]
  command = "bundle install && bundle exec jekyll build"
    publish = "_site"

[build.processing]
  skip_processing = true

[build.lifecycle]
  onPreBuild = "echo 'onPreBuild lifecycle event started' && uname -a && gcc --version && sudo apt-get update && sudo apt-get install -y build-essential"

[[plugins]]
  package = "@netlify/plugin-ruby-bundler"